default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  host: localhost
  database: animals_development
test:
  <<: *default
  database: animals_test
production:
  <<: *default
  database: animals_production
